"""Background intelligence engine for autonomous prompt improvement.

Watches prompt state, produces real-time recommendations (whispers), and
pre-caches variations for sections the user dwells on. Works without any
TUI framework -- consumable from both a Textual app and a plain CLI.
"""

from __future__ import annotations

import asyncio
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from prompt_master.tui.attention import DwellEvent, DeepDwellEvent
from prompt_master.tui.cache import LRUCache
from prompt_master.tui.realtime_scorer import (
    SectionScore,
    compute_overall_score,
    detect_decomposition,
    get_weakness_feedback,
    score_sections,
)


# ── Data structures ──────────────────────────────────────────────────────────

@dataclass
class Whisper:
    """A lightweight recommendation surfaced to the user.

    Whispers are short, context-aware nudges generated by the intelligence
    layer. They appear in the TUI as subtle hints, not blocking dialogs.

    Attributes:
        text: Human-readable suggestion text.
        section: The section this whisper relates to.
        priority: 0=low, 1=medium, 2=high.
        whisper_type: Category -- one of "score", "improvement", "coherence",
                      "decomposition", "variations_ready".
    """
    text: str
    section: str
    priority: int        # 0=low, 1=medium, 2=high
    whisper_type: str    # "score", "improvement", "coherence", "decomposition", "variations_ready"

    def __repr__(self) -> str:
        prio = ["low", "medium", "high"][min(self.priority, 2)]
        return f"Whisper({prio}, {self.whisper_type}, {self.section!r}: {self.text!r})"


@dataclass
class IntelligenceState:
    """Shared mutable state consumed by the intelligence worker.

    This is the single source of truth for the current prompt, scores,
    cached variations, and pending whispers. Both the TUI and the worker
    read/write this structure.
    """
    prompt_sections: Dict[str, str] = field(default_factory=dict)
    section_scores: Dict[str, SectionScore] = field(default_factory=dict)
    overall_score: float = 0.0
    cached_variations: Dict[str, List[Any]] = field(default_factory=dict)
    pending_whispers: deque = field(default_factory=deque)
    active_section: Optional[str] = None
    edit_generation: int = 0
    tokens_used: int = 0
    token_budget: int = 50000


# ── Coherence checking ───────────────────────────────────────────────────────

def _check_coherence(sections: Dict[str, str]) -> List[Whisper]:
    """Check for cross-section coherence issues.

    Looks for mismatches between sections that should be aligned:
    - Role mentions a domain but Task is about something else
    - Output Format specifies code but Task is about prose (or vice versa)
    - Requirements contradict format expectations

    Returns:
        List of coherence whispers (may be empty).
    """
    whispers: List[Whisper] = []
    role = sections.get("Role", "").lower()
    task = sections.get("Task", "").lower()
    fmt = sections.get("Output Format", "").lower()

    # Code role but non-code task
    code_role_signals = ["software engineer", "developer", "programmer", "coder"]
    creative_task_signals = ["story", "poem", "essay", "narrative", "fiction", "creative writing"]

    role_is_code = any(s in role for s in code_role_signals)
    task_is_creative = any(s in task for s in creative_task_signals)

    if role_is_code and task_is_creative:
        whispers.append(Whisper(
            text="Role is code-focused but task is creative -- consider aligning them.",
            section="Role",
            priority=1,
            whisper_type="coherence",
        ))

    # Format says "code" but task is clearly non-code
    format_wants_code = any(s in fmt for s in ["code block", "fenced", "```", "implementation"])
    task_wants_prose = any(s in task for s in ["essay", "article", "blog post", "letter"])

    if format_wants_code and task_wants_prose:
        whispers.append(Whisper(
            text="Output format specifies code but task requests prose -- double-check alignment.",
            section="Output Format",
            priority=1,
            whisper_type="coherence",
        ))

    # Role is creative but format is highly structured/technical
    creative_role_signals = ["creative writer", "novelist", "poet", "storyteller"]
    structured_format_signals = ["json", "yaml", "xml", "csv", "table", "report"]

    role_is_creative = any(s in role for s in creative_role_signals)
    format_is_structured = any(s in fmt for s in structured_format_signals)

    if role_is_creative and format_is_structured:
        whispers.append(Whisper(
            text="Creative role paired with highly structured output format -- intentional?",
            section="Output Format",
            priority=0,
            whisper_type="coherence",
        ))

    return whispers


# ── Intelligence Worker ──────────────────────────────────────────────────────

class IntelligenceWorker:
    """Background worker that watches prompt state and produces recommendations.

    The worker is designed to be driven by explicit calls from the UI layer
    rather than running its own event loop. This keeps it framework-agnostic.

    Usage::

        state = IntelligenceState()
        worker = IntelligenceWorker(state, target="code")

        # When user edits a section:
        worker.on_section_changed("Role", "You are a senior Python engineer...")

        # When attention tracker fires a dwell:
        worker.on_dwell("Role")

        # Poll for whispers:
        whisper = worker.get_next_whisper()

    Args:
        state: Shared intelligence state.
        client: Optional ``ClaudeClient`` for API-backed variation generation.
        target: Optimization target (e.g. "general", "code", "creative").
    """

    def __init__(
        self,
        state: IntelligenceState,
        client: Any = None,
        target: str = "general",
    ) -> None:
        self.state = state
        self.client = client
        self.target = target
        self._cache = LRUCache(max_size=50)
        self._last_decomposition_check: Optional[str] = None

    # ── Section change handling ──────────────────────────────────────────

    def on_section_changed(self, section: str, content: str) -> None:
        """Called when the user edits a section. Triggers re-scoring and analysis.

        This is the main entry point for reacting to edits. It:
        1. Updates the shared state with the new content.
        2. Re-scores all sections locally (fast, <5ms).
        3. Queues whispers for weak sections.
        4. Checks for cross-section coherence issues.
        5. Checks for decomposition opportunities in the Task.

        Args:
            section: Name of the edited section (e.g. "Role").
            content: New content of the section.
        """
        self.state.prompt_sections[section] = content
        self.state.edit_generation += 1

        # 1. Re-score all sections
        self.state.section_scores = score_sections(self.state.prompt_sections, self.target)
        self.state.overall_score = compute_overall_score(self.state.section_scores)

        # 2. Queue whispers for weak sections
        for suggestion in get_weakness_feedback(self.state.section_scores):
            # Extract section name from the suggestion format "[Section] ..."
            whisper_section = section  # default to the changed section
            if suggestion.startswith("[") and "]" in suggestion:
                whisper_section = suggestion[1:suggestion.index("]")]

            self.state.pending_whispers.append(Whisper(
                text=suggestion,
                section=whisper_section,
                priority=1,
                whisper_type="improvement",
            ))

        # 3. Cross-section coherence
        coherence_whispers = _check_coherence(self.state.prompt_sections)
        for w in coherence_whispers:
            self.state.pending_whispers.append(w)

        # 4. Decomposition check (only for Task section, debounced)
        if section == "Task":
            suggestion = detect_decomposition(content)
            if suggestion and suggestion != self._last_decomposition_check:
                self._last_decomposition_check = suggestion
                self.state.pending_whispers.append(Whisper(
                    text=suggestion,
                    section="Task",
                    priority=2,
                    whisper_type="decomposition",
                ))

        # Invalidate cached variations for this section
        cache_key = self._cache.content_key(section, content)
        if cache_key not in self._cache:
            self.state.cached_variations.pop(section, None)

    # ── Attention event handlers ─────────────────────────────────────────

    def on_dwell(self, section: str) -> None:
        """Called on DwellEvent (~800ms focus). Queues a score whisper.

        Args:
            section: The section the user is dwelling on.
        """
        self.state.active_section = section
        ss = self.state.section_scores.get(section)
        if ss is not None:
            priority = 2 if ss.score < 4.0 else (1 if ss.score < 7.0 else 0)
            self.state.pending_whispers.append(Whisper(
                text=f"{section}: {ss.score:.0f}/10 -- {ss.feedback}",
                section=section,
                priority=priority,
                whisper_type="score",
            ))

    def on_deep_dwell(self, section: str) -> None:
        """Called on DeepDwellEvent (~2500ms focus). Pre-generates variations.

        If a client is available and the token budget allows, this triggers
        async variation generation for the focused section. Otherwise, it
        checks the cache for previously generated variations.

        Args:
            section: The section the user has been dwelling on.
        """
        self.state.active_section = section
        content = self.state.prompt_sections.get(section, "")
        if not content:
            return

        # Check cache first
        cache_key = self._cache.content_key(section, content)
        cached = self._cache.get(cache_key)
        if cached is not None:
            self.state.cached_variations[section] = cached
            self.state.pending_whispers.append(Whisper(
                text=f"Variations ready for {section} (cached).",
                section=section,
                priority=0,
                whisper_type="variations_ready",
            ))
            return

        # If no client or budget exhausted, skip API call
        if self.client is None:
            return
        if self.state.tokens_used >= self.state.token_budget:
            return

        # Mark that we'd like to generate variations (async generation
        # would be triggered by the TUI layer calling generate_variations_async)
        self.state.pending_whispers.append(Whisper(
            text=f"Dwelling on {section} -- variations will be pre-generated.",
            section=section,
            priority=0,
            whisper_type="variations_ready",
        ))

    async def generate_variations_async(self, section: str) -> Optional[List[str]]:
        """Asynchronously generate variations for a section via the API.

        This is intended to be called from an async TUI event loop. It
        respects the token budget and caches results.

        Args:
            section: Section to generate variations for.

        Returns:
            List of variation strings, or None if generation was skipped.
        """
        content = self.state.prompt_sections.get(section, "")
        if not content or self.client is None:
            return None

        if self.state.tokens_used >= self.state.token_budget:
            return None

        cache_key = self._cache.content_key(section, content)
        cached = self._cache.get(cache_key)
        if cached is not None:
            return cached

        # Run the blocking API call in a thread pool
        try:
            from prompt_master.optimizer import META_SYSTEM_PROMPT
            user_msg = (
                f"Generate 3 alternative versions of this '{section}' section. "
                f"Each should be meaningfully different.\n\n"
                f"Current content:\n{content}\n\n"
                f"Output each variation on its own, separated by '---'."
            )
            response = await asyncio.get_event_loop().run_in_executor(
                None,
                lambda: self.client.generate(META_SYSTEM_PROMPT, user_msg, max_tokens=1024),
            )
            variations = [v.strip() for v in response.split("---") if v.strip()]

            # Track token usage (approximate)
            self.state.tokens_used += len(content.split()) + len(response.split())

            # Cache the result
            self._cache.put(cache_key, variations)
            self.state.cached_variations[section] = variations

            self.state.pending_whispers.append(Whisper(
                text=f"{len(variations)} variation(s) ready for {section}.",
                section=section,
                priority=1,
                whisper_type="variations_ready",
            ))

            return variations

        except Exception:
            # Silently fail -- variations are a nice-to-have
            return None

    # ── Whisper management ───────────────────────────────────────────────

    def get_next_whisper(self) -> Optional[Whisper]:
        """Pop the highest-priority whisper from the queue.

        Returns:
            The next ``Whisper`` to display, or None if the queue is empty.
        """
        if not self.state.pending_whispers:
            return None

        # Find highest priority
        best_idx = 0
        best_priority = self.state.pending_whispers[0].priority
        for i, w in enumerate(self.state.pending_whispers):
            if w.priority > best_priority:
                best_priority = w.priority
                best_idx = i

        # Remove and return it
        # deque doesn't support pop at arbitrary index, so we rotate
        whispers = self.state.pending_whispers
        whispers.rotate(-best_idx)
        result = whispers.popleft()
        whispers.rotate(best_idx)
        return result

    def get_cached_variations(self, section: str) -> Optional[List[Any]]:
        """Return pre-cached variations for a section, if available.

        Args:
            section: Section name.

        Returns:
            List of variations, or None if nothing is cached.
        """
        return self.state.cached_variations.get(section)

    def drain_whispers(self, max_count: int = 10) -> List[Whisper]:
        """Drain up to ``max_count`` whispers from the queue, highest priority first.

        Args:
            max_count: Maximum number of whispers to return.

        Returns:
            List of whispers ordered by priority (highest first).
        """
        result: List[Whisper] = []
        for _ in range(max_count):
            w = self.get_next_whisper()
            if w is None:
                break
            result.append(w)
        return result

    def reset(self) -> None:
        """Reset all state and caches."""
        self.state.pending_whispers.clear()
        self.state.section_scores.clear()
        self.state.cached_variations.clear()
        self.state.overall_score = 0.0
        self.state.edit_generation = 0
        self.state.tokens_used = 0
        self._cache.clear()
        self._last_decomposition_check = None
