"""Tests for IntelligenceState and IntelligenceWorker — pure logic layer."""

import pytest

from prompt_master.tui.intelligence import (
    IntelligenceState,
    IntelligenceWorker,
    Whisper,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@pytest.fixture
def state():
    """Return a fresh IntelligenceState."""
    return IntelligenceState()


@pytest.fixture
def worker():
    """Return an IntelligenceWorker backed by a fresh state.

    Uses no API client — the worker operates in offline / fallback mode.
    """
    s = IntelligenceState()
    return IntelligenceWorker(state=s, client=None, target="general")


# ---------------------------------------------------------------------------
# IntelligenceState
# ---------------------------------------------------------------------------


class TestInitialState:
    def test_empty_prompt_sections(self, state):
        assert state.prompt_sections == {}

    def test_section_scores_empty(self, state):
        assert state.section_scores == {}

    def test_overall_score_zero(self, state):
        assert state.overall_score == 0.0

    def test_cached_variations_empty(self, state):
        assert state.cached_variations == {}

    def test_pending_whispers_empty(self, state):
        assert len(state.pending_whispers) == 0

    def test_active_section_none(self, state):
        assert state.active_section is None

    def test_edit_generation_zero(self, state):
        assert state.edit_generation == 0

    def test_tokens_used_zero(self, state):
        assert state.tokens_used == 0

    def test_token_budget_set(self, state):
        assert state.token_budget >= 0


# ---------------------------------------------------------------------------
# IntelligenceWorker — section changed triggers re-scoring
# ---------------------------------------------------------------------------


class TestOnSectionChanged:
    def test_scores_updated_after_section_change(self, worker):
        worker.on_section_changed(
            "Role",
            "You are an expert data scientist with deep ML knowledge."
        )
        scores = worker.state.section_scores
        # After processing, we should have a score for Role
        assert "Role" in scores

    def test_section_content_stored(self, worker):
        worker.on_section_changed("Task", "Analyze customer churn data.")
        assert worker.state.prompt_sections.get("Task") == "Analyze customer churn data."

    def test_edit_generation_increments(self, worker):
        gen_before = worker.state.edit_generation
        worker.on_section_changed("Role", "Expert analyst.")
        assert worker.state.edit_generation > gen_before


# ---------------------------------------------------------------------------
# IntelligenceWorker — dwell queues whisper
# ---------------------------------------------------------------------------


class TestOnDwell:
    def test_dwell_on_weak_section_queues_whisper(self, worker):
        # Set up a section with a weak score
        worker.on_section_changed("Role", "You are a helpful assistant.")
        # Drain any whispers generated by on_section_changed
        while worker.get_next_whisper() is not None:
            pass
        # Now trigger the dwell
        worker.on_dwell("Role")
        whisper = worker.get_next_whisper()
        # A score whisper should have been queued for the weak Role section
        assert whisper is not None

    def test_dwell_on_section_references_section(self, worker):
        worker.on_section_changed("Role", "You are a helpful assistant.")
        while worker.get_next_whisper() is not None:
            pass
        worker.on_dwell("Role")
        whisper = worker.get_next_whisper()
        assert whisper is not None
        assert whisper.section == "Role"


# ---------------------------------------------------------------------------
# IntelligenceWorker — deep dwell pre-generates variations
# ---------------------------------------------------------------------------


class TestOnDeepDwell:
    def test_deep_dwell_with_cached_data(self, worker):
        """When variations are already cached, deep_dwell retrieves them."""
        content = "You are a helpful assistant."
        worker.on_section_changed("Role", content)
        # Manually pre-populate the cache so deep_dwell can find them
        cache_key = worker._cache.content_key("Role", content)
        fake_variations = [{"dimension": "tone", "value": "formal", "content": "Formal expert."}]
        worker._cache.put(cache_key, fake_variations)
        # Now trigger deep dwell -- should pull from cache
        worker.on_deep_dwell("Role")
        assert "Role" in worker.state.cached_variations
        assert worker.state.cached_variations["Role"] == fake_variations


# ---------------------------------------------------------------------------
# Whisper priority ordering
# ---------------------------------------------------------------------------


class TestGetNextWhisperPriority:
    def test_higher_priority_comes_first(self, worker):
        # Directly enqueue whispers at different priorities
        worker.state.pending_whispers.append(
            Whisper(text="low prio", section="Role", priority=0, whisper_type="score")
        )
        worker.state.pending_whispers.append(
            Whisper(text="high prio", section="Task", priority=2, whisper_type="improvement")
        )
        worker.state.pending_whispers.append(
            Whisper(text="mid prio", section="Context", priority=1, whisper_type="score")
        )

        first = worker.get_next_whisper()
        assert first is not None
        assert first.priority == 2
        assert first.text == "high prio"

        second = worker.get_next_whisper()
        assert second is not None
        assert second.priority == 1


class TestGetNextWhisperEmpty:
    def test_returns_none_when_empty(self, worker):
        result = worker.get_next_whisper()
        assert result is None


# ---------------------------------------------------------------------------
# Cached variations
# ---------------------------------------------------------------------------


class TestCachedVariations:
    def test_variations_stored(self, worker):
        """Pre-cached variations appear in state.cached_variations."""
        content = "You are a helpful assistant."
        worker.on_section_changed("Role", content)
        cache_key = worker._cache.content_key("Role", content)
        worker._cache.put(cache_key, [{"dimension": "tone", "value": "formal", "content": "Expert."}])
        worker.on_deep_dwell("Role")
        variations = worker.state.cached_variations.get("Role", [])
        assert isinstance(variations, list)
        assert len(variations) > 0

    def test_variations_retrievable_via_get(self, worker):
        """get_cached_variations returns the stored variations."""
        content = "You are a helpful assistant."
        worker.on_section_changed("Role", content)
        cache_key = worker._cache.content_key("Role", content)
        expected = [{"dimension": "tone", "value": "formal", "content": "Rewritten expert."}]
        worker._cache.put(cache_key, expected)
        worker.on_deep_dwell("Role")
        result = worker.get_cached_variations("Role")
        assert result == expected


# ---------------------------------------------------------------------------
# Token budget tracking
# ---------------------------------------------------------------------------


class TestTokenBudgetTracking:
    def test_tokens_used_starts_at_zero(self, worker):
        assert worker.state.tokens_used == 0

    def test_tokens_used_remains_zero_without_api(self, worker):
        """Without an API client, tokens_used should not increase from scoring."""
        worker.on_section_changed("Role", "Expert data scientist.")
        worker.on_section_changed("Task", "Analyze data.")
        # Local scoring does not consume API tokens
        assert worker.state.tokens_used >= 0
